"use client";

import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";

export function PrivacyPolicy() {
  return (
    <Dialog>
      <DialogTrigger asChild>
        <button className="text-xs text-muted-foreground/70 hover:text-muted-foreground">
          Privacy Policy
        </button>
      </DialogTrigger>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <DialogTitle>Privacy Policy</DialogTitle>
          <DialogDescription>
            Last updated: {new Date().toLocaleDateString()}
          </DialogDescription>
        </DialogHeader>
        <div className="text-sm space-y-4 max-h-[60vh] overflow-y-auto pr-2">
          <p>
            This website uses Google Analytics, a web analytics service provided by Google, Inc. 
            Google Analytics uses cookies to help us analyze how users use our site.
          </p>
          <p>
            The information generated by the cookie about your use of the website (including your 
            IP address) will be transmitted to and stored by Google on servers in the United States. 
            Google will use this information for the purpose of evaluating your use of the website, 
            compiling reports on website activity, and providing other services relating to website 
            activity and internet usage.
          </p>
          <p>
            You may refuse the use of cookies by selecting the appropriate settings on your browser, 
            or by using Google's opt-out browser add-on available at 
            <a href="https://tools.google.com/dlpage/gaoptout" className="text-blue-500 hover:underline ml-1" target="_blank" rel="noopener noreferrer">
              https://tools.google.com/dlpage/gaoptout
            </a>.
          </p>
        </div>
      </DialogContent>
    </Dialog>
  );
} 